import time
import sys
import os

# Fix Windows terminal encoding
if os.name == 'nt':
    os.system('chcp 65001 >nul 2>&1')
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

def type_out(text, speed=0.03):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def type_fast(text):
    type_out(text, 0.015)

def pause(seconds=0.5):
    time.sleep(seconds)

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

def main():
    clear()
    pause(0.5)

    # Boot sequence
    print()
    type_out("   ______  __    ___   __  __ ____   ______", 0.008)
    type_out("  / ____/ / /   /   | / / / // __ \\ / ____/", 0.008)
    type_out(" / /     / /   / /| |/ / / // / / // __/   ", 0.008)
    type_out("/ /___  / /___/ ___ / /_/ // /_/ // /___   ", 0.008)
    type_out("\\____/ /_____/_/  |_\\____//_____//_____/   ", 0.008)
    pause(0.5)

    print()
    type_out("  =====================================================", 0.01)
    type_out("       PERSONAL AI SYSTEM  //  BUILT BY HAZEM", 0.025)
    type_out("  =====================================================", 0.01)
    pause(0.8)

    print()
    type_out("  > INITIALIZING ....................................... OK", 0.015)
    pause(0.2)
    type_out("  > LOADING CLAUDE AI ENGINE ............................ OK", 0.015)
    pause(0.2)
    type_out("  > MODEL: Claude Opus 4.7 (Anthropic) ................. ACTIVE", 0.015)
    pause(0.2)
    type_out("  > RUNTIME: VS Code + Terminal ........................ CONNECTED", 0.015)
    pause(0.2)
    type_out("  > LANGUAGE: Python 3 ................................. READY", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: WEB DESIGN & DEPLOYMENT ................ LOADED", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: SOCIAL MEDIA MANAGER (13 platforms) .... LOADED", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: YOUTUBE SEO ENGINE ...................... LOADED", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: BUSINESS & BRANDING .................... LOADED", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: AUTOMATION & SCRIPTING .................. LOADED", 0.015)
    pause(0.2)
    type_out("  > SKILL PACK: DOCUMENTS & DATA ....................... LOADED", 0.015)
    pause(0.2)
    type_out("  > FILE SYSTEM ACCESS ................................. FULL", 0.015)
    pause(0.2)
    type_out("  > INTERNET ACCESS (APIs, scraping, deployment) ....... FULL", 0.015)
    pause(0.2)
    type_out("  > SOFTWARE INSTALLER ................................. ARMED", 0.015)
    pause(0.5)

    print()
    type_out("  ALL SYSTEMS GO.", 0.04)
    pause(0.8)

    print()
    print("  -----------------------------------------------------")
    pause(0.5)

    print()
    type_out("  Welcome to your machine.", 0.04)
    pause(1.0)

    print()
    type_out("  This isn't a chatbot. This isn't ChatGPT in a browser.", 0.025)
    type_out("  This is Claude — one of the most advanced AI systems", 0.025)
    type_out("  on the planet — wired directly into your computer.", 0.025)
    pause(0.5)

    print()
    type_out("  It can read, write, and edit any file on your machine.", 0.025)
    type_out("  It can install software. It can run code. It can hit", 0.025)
    type_out("  any API on the internet. It can build full applications,", 0.025)
    type_out("  deploy them live, and automate them to run without you.", 0.025)
    pause(0.5)

    print()
    type_out("  Think of it as a full development team sitting at your", 0.025)
    type_out("  keyboard — designer, developer, marketer, data analyst,", 0.025)
    type_out("  copywriter, SEO specialist — all in one. The same work", 0.025)
    type_out("  companies pay $100K+ a year for, you now have on demand.", 0.025)
    pause(0.5)

    print()
    type_out("  Hazem built this for you personally. Everything is", 0.025)
    type_out("  loaded and ready. You don't need to know how to code.", 0.025)
    type_out("  You just tell it what you want — it handles the rest.", 0.025)
    pause(1.0)

    # === WHAT'S LOADED ===
    print()
    type_out("  =====================================================", 0.01)
    type_out("       WHAT'S LOADED RIGHT NOW", 0.03)
    type_out("  =====================================================", 0.01)
    pause(0.5)

    print()
    type_out("  [WEB DESIGN & DEPLOYMENT]", 0.02)
    type_fast("    - Build professional websites from scratch")
    type_fast("    - Dark premium designs with animations & effects")
    type_fast("    - Landing pages, portfolios, business sites, campaigns")
    type_fast("    - Mobile-responsive — works perfect on every phone")
    type_fast("    - Deploy live to the internet for free (GitHub Pages)")
    type_fast("    - Custom domains with SSL (the lock icon)")
    type_fast("    - SEO so Google actually finds you")
    pause(0.3)

    print()
    type_out("  [SOCIAL MEDIA MANAGER — 13 PLATFORMS]", 0.02)
    type_fast("    - Post to YouTube, Instagram, TikTok, Twitter/X,")
    type_fast("      LinkedIn, Facebook, Threads, Pinterest, Reddit,")
    type_fast("      Bluesky, Google Business, Telegram, Snapchat")
    type_fast("    - Unique content per platform (never copy-paste)")
    type_fast("    - Schedule posts, drafts, cross-post everywhere")
    type_fast("    - YouTube Shorts + Reels + TikTok in one shot")
    type_fast("    - Full YouTube SEO: titles, tags, timestamps, thumbnails")
    type_fast("    - Powered by Late API (getlate.dev)")
    pause(0.3)

    print()
    type_out("  [BUSINESS & BRANDING]", 0.02)
    type_fast("    - Generate business ideas and full brand strategies")
    type_fast("    - Business plans, pitch decks, investor proposals")
    type_fast("    - Logo concepts and brand identity guidelines")
    type_fast("    - Market research and competitor analysis")
    type_fast("    - Content strategies and marketing funnels")
    pause(0.3)

    print()
    type_out("  [DOCUMENTS & DATA]", 0.02)
    type_fast("    - Professional emails, cold outreach sequences")
    type_fast("    - PowerPoint presentations")
    type_fast("    - Excel spreadsheets with formulas and charts")
    type_fast("    - Word documents, contracts, reports, invoices")
    type_fast("    - CSV files, data tables, financial models")
    pause(0.3)

    print()
    type_out("  [AUTOMATION & SCRIPTS]", 0.02)
    type_fast("    - Auto-update websites with live data feeds")
    type_fast("    - Batch process and compress hundreds of images")
    type_fast("    - Web scraping — pull data from any website")
    type_fast("    - File management — organize, rename, sort files")
    type_fast("    - Scheduled tasks that run on their own 24/7")
    type_fast("    - Bots (Telegram, Discord, customer service)")
    pause(0.8)

    # === TIP OF THE ICEBERG ===
    print()
    type_out("  =====================================================", 0.01)
    type_out("       BUT THAT'S JUST THE TIP OF THE ICEBERG", 0.03)
    type_out("  =====================================================", 0.01)
    pause(0.8)

    print()
    type_out("  Everything above is what's pre-loaded in your skill", 0.025)
    type_out("  packs right now. But Claude isn't limited to what's", 0.025)
    type_out("  in these files. It can learn anything, build anything,", 0.025)
    type_out("  connect to anything. Here's what else is possible:", 0.025)
    pause(0.6)

    print()
    type_out("  [INCOME STREAM: WEB DESIGN AGENCY]", 0.02)
    type_fast("    - Charge clients $500-2,500 per website")
    type_fast("    - Claude builds the entire site in one session")
    type_fast("    - Monthly maintenance retainers ($50-200/mo per client)")
    type_fast("    - You sell it, Claude builds it. Near 100% margin.")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: SOCIAL MEDIA MANAGEMENT]", 0.02)
    type_fast("    - Charge $500-2,000/mo per client")
    type_fast("    - Claude writes content, schedules, posts to all platforms")
    type_fast("    - Manage 10+ clients from this one terminal")
    type_fast("    - Unique content per platform, never generic")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: E-COMMERCE]", 0.02)
    type_fast("    - Product listings across eBay, Amazon, Shopify")
    type_fast("    - Price monitoring and competitor tracking")
    type_fast("    - Inventory sync across multiple stores")
    type_fast("    - Automated order tracking and customer emails")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: EMAIL MARKETING]", 0.02)
    type_fast("    - Connect to SendGrid, Mailchimp, Brevo APIs")
    type_fast("    - Build email templates and automated sequences")
    type_fast("    - Charge clients for setup + monthly management")
    type_fast("    - Claude writes the copy, builds the flow, sends it")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: CONTENT CREATION]", 0.02)
    type_fast("    - Blog posts optimized for Google SEO")
    type_fast("    - YouTube scripts and full video packages")
    type_fast("    - LinkedIn thought leadership ghostwriting")
    type_fast("    - Newsletter writing — charge per issue or monthly")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: DATA & SCRAPING SERVICES]", 0.02)
    type_fast("    - Scrape leads, prices, contacts, product data")
    type_fast("    - Build databases of business intelligence")
    type_fast("    - Price monitoring dashboards for clients")
    type_fast("    - Market research reports with real data")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: BOTS & AUTOMATION]", 0.02)
    type_fast("    - Telegram bots for customer service")
    type_fast("    - Discord bots for communities")
    type_fast("    - Lead capture bots on client websites")
    type_fast("    - Chatbots that qualify prospects 24/7")
    pause(0.3)

    print()
    type_out("  [INCOME STREAM: SaaS & WEB APPS]", 0.02)
    type_fast("    - Booking systems, client portals, dashboards")
    type_fast("    - Deploy on free hosting (Vercel, Render, Railway)")
    type_fast("    - Charge monthly access — recurring revenue")
    type_fast("    - Build once, get paid every month")
    pause(0.3)

    print()
    type_out("  [API POWER — CONNECT ANYTHING TO ANYTHING]", 0.02)
    type_fast("    - Stripe / PayPal for payment processing")
    type_fast("    - Google Sheets as a free database")
    type_fast("    - Twilio for SMS and WhatsApp notifications")
    type_fast("    - HubSpot / Salesforce CRM integration")
    type_fast("    - Google Calendar for booking systems")
    type_fast("    - OpenAI / Anthropic for AI-powered features")
    type_fast("    - Any service with an API — Claude can connect it")
    pause(0.8)

    # === UNDER THE HOOD ===
    print()
    type_out("  =====================================================", 0.01)
    type_out("       WHAT'S UNDER THE HOOD", 0.03)
    type_out("  =====================================================", 0.01)
    pause(0.5)

    print()
    type_out("  VS Code is the app you're in right now. It's the same", 0.025)
    type_out("  tool developers at Google, Apple, Microsoft, and every", 0.025)
    type_out("  startup on the planet use to build their products.", 0.025)
    type_out("  Now you have it.", 0.025)
    pause(0.4)

    print()
    type_out("  Claude is the AI engine. Built by Anthropic — the same", 0.025)
    type_out("  company founded by former OpenAI researchers. It doesn't", 0.025)
    type_out("  just answer questions — it reads your files, writes code,", 0.025)
    type_out("  runs programs, installs tools, deploys websites, and", 0.025)
    type_out("  manages your entire workflow from this terminal.", 0.025)
    pause(0.4)

    print()
    type_out("  Python is the language behind most of the AI world —", 0.025)
    type_out("  ChatGPT, Instagram, YouTube, Netflix, NASA, SpaceX.", 0.025)
    type_out("  When Claude needs to compress images, scrape the web,", 0.025)
    type_out("  process data, or automate tasks — it writes Python", 0.025)
    type_out("  and runs it right here on your machine.", 0.025)
    pause(0.4)

    print()
    type_out("  Git & GitHub are how every developer ships code.", 0.025)
    type_out("  When you build a website, Claude pushes it to GitHub", 0.025)
    type_out("  and it goes live on the internet — free, instant,", 0.025)
    type_out("  with a custom domain and SSL.", 0.025)
    pause(0.4)

    print()
    type_out("  APIs are how software talks to other software. Stripe", 0.025)
    type_out("  for payments, Twilio for texts, Late for social media,", 0.025)
    type_out("  Google for data — Claude can connect to all of them", 0.025)
    type_out("  and make them work together. That's what companies", 0.025)
    type_out("  pay developers six figures to do.", 0.025)
    pause(0.4)

    print()
    type_out("  If any tool isn't installed yet — don't worry.", 0.025)
    type_out("  Claude detects what's missing and installs everything", 0.025)
    type_out("  automatically. You literally just talk to it.", 0.025)
    pause(1.0)

    # === HOW TO USE ===
    print()
    type_out("  =====================================================", 0.01)
    type_out("       HOW TO USE THIS", 0.03)
    type_out("  =====================================================", 0.01)
    pause(0.5)

    print()
    type_out("  Just type what you want. Plain English. Examples:", 0.025)
    pause(0.3)

    print()
    type_fast('    "Build me a website for my barbershop"')
    type_fast('    "Post this video to YouTube, Instagram, and TikTok"')
    type_fast('    "Write a cold email sequence for my agency"')
    type_fast('    "Create a business plan for a clothing brand"')
    type_fast('    "Scrape all the restaurants in my city from Google"')
    type_fast('    "Make me a PowerPoint pitch deck for investors"')
    type_fast('    "Schedule posts for the whole week on all platforms"')
    type_fast('    "Build me a booking system for my service business"')
    type_fast('    "Compress all the images in my photos folder"')
    type_fast('    "Create a full YouTube content package for this video"')
    type_fast('    "Build me an Excel spreadsheet to track my finances"')
    type_fast('    "Set up a Telegram bot for customer inquiries"')
    type_fast('    "Give me 10 business ideas I can start this week"')
    pause(0.8)

    print()
    type_out("  If Claude needs a tool that isn't installed, it installs", 0.025)
    type_out("  it. If it needs an API key, it tells you where to get", 0.025)
    type_out("  one. If something breaks, it fixes it. You just talk.", 0.025)
    pause(1.0)

    # === CLOSING ===
    print()
    print("  -----------------------------------------------------")
    pause(0.5)
    print()
    type_out("  This system was built by Hazem.", 0.04)
    pause(0.3)
    type_out("  Powered by Claude (Anthropic) + Python + VS Code.", 0.03)
    pause(0.3)
    type_out("  No limits. No monthly fees for the tools. Just build.", 0.03)
    pause(0.3)

    print()
    type_out("  The people charging $5K for websites, $2K/mo for social", 0.025)
    type_out("  media, $3K for e-commerce setups — they're using the", 0.025)
    type_out("  same tools sitting on your machine right now.", 0.025)
    type_out("  The only difference is you have Claude.", 0.025)
    pause(0.8)

    print()
    type_out("  Ready when you are.", 0.05)
    print()
    type_out("  =====================================================", 0.01)
    print()

if __name__ == '__main__':
    main()
